import {StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
export default StyleSheet.create({
  bg: {
    flex: 1,
    height: '45%',
  },
  BigText: {
    color: '#fff',
    fontSize: 35,
    paddingLeft: 30,
    fontFamily: 'Poppins-Bold',
    marginTop: 0,
  },
  Subheaing: {
    color: '#fff',
    fontSize: 14,
    paddingLeft: 30,
    fontFamily: 'Poppins-Medium',
  },
  Empty: {
    alignSelf: 'center',
    marginTop: 100,
    color: 'red',
    fontFamily: 'Poppins-Medium',
  },
  input: {
    height: hp(8),
    width: wp(85),
    alignSelf: 'center',
    borderRadius: 10,
    color: 'white',
    backgroundColor: '#5B77D0',
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#fff',
    marginTop: 0,
  },
  smallLogo: {
    height: 50,
    width: 60,
    alignSelf: 'flex-end',
    right: 10,
    opacity: 0.3,
    top: 10,
  },
  HeaderTopView: {
    flexDirection: 'row',
    width: wp(100),
    paddingHorizontal: 15,
    height: hp(5),
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  CardTxt: {
    fontSize: 16,
    fontFamily: 'Poppins-Medium',
    color: '#15096F',
  },
  ActiveCardView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '90%',
    paddingHorizontal: 20,
    height: hp(9),
    borderWidth: 0,
    marginBottom: 15,
    alignSelf: 'center',
    borderRadius: 15,
    elevation: 5,
    backgroundColor: '#5B77D0',
  },
  Btn: {
    height: hp(8),
    width: wp('90%'),
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    backgroundColor: '#5B77D0',
  },
  Btn: {
    height: hp(8),
    width: wp('90%'),
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    backgroundColor: '#5B77D0',
  },
  BtnTxt: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  BtnSave: {
    height: hp(8),
    width: wp('90%'),
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    backgroundColor: '#F4F4FA',
    borderWidth: 2,
    borderColor: '#5B77D0',
    marginTop: 10,
    marginBottom: 10,
  },
  BtnTxtSave: {
    color: '#5B77D0',
    fontSize: 18,
    fontWeight: 'bold',
    // opacity: 0.4
  },
});
