import {StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
export default StyleSheet.create({
  bg: {
    height: hp('50%'),
    flex: 1,
  },
  MainView: {
    flex: 1,
    backgroundColor: '#fff',
    paddingHorizontal: 15,
  },
  BigText: {
    color: '#fff',
    fontSize: 30,
    alignSelf: 'center',
    fontFamily: 'Poppins-SemiBold',
  },
  MediumText: {
    color: 'white',
    fontSize: 20,
    alignSelf: 'center',
    marginTop: 10,
    textAlign: 'center',
  },
  SmallText: {
    color: '#5B77D0',
    fontSize: 14,
    alignSelf: 'center',
    marginTop: 10,
  },
  SmallTextBold: {
    color: '#5B77D0',
    fontSize: 14,
    alignSelf: 'center',
    marginTop: 10,
    fontWeight: 'bold',
  },
  input: {
    height: hp(7),
    width: wp(85),
    borderWidth: 1,
    borderColor: '#fff',
    alignSelf: 'center',
    borderRadius: 10,
    color: 'black',
    backgroundColor: '#5B77D0',
    marginTop: 20,
    paddingHorizontal: 12,
    fontFamily: 'Poppins-Regular',
    justifyContent: 'center',
    alignItems: 'center',
  },
  parent: {
    height: '40%',
    width: '100%',
    transform: [{scaleX: 1.3}],
    borderBottomStartRadius: 1000,
    borderBottomEndRadius: 1000,
    overlayColor: 'white',
    overflow: 'hidden',
  },
  child: {
    flex: 1,
    overlayColor: 'white',
    backgroundColor: '#5B77D0',
    alignItems: 'center',
  },
  smallLogo: {
    height: 40,
    width: 60,
    alignSelf: 'flex-end',
    opacity: 0.3,
  },
  smallCard: {
    flex: 1,
    height: hp(9),
    width: wp(86),
    alignSelf: 'center',
    borderRadius: 10,
    borderWidth: 0,
    marginTop: 5,
    marginBottom: 10,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    elevation: 2,
  },
  SmallRoundPic: {
    height: hp(8),
    width: hp(8),
    borderRadius: 100,
  },
  HeaderTopView: {
    height: hp(6),
    width: wp(100),
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  name: {
    fontSize: 16,
    fontFamily: 'Poppins-SemiBold',
    color: '#15096F',
  },
  Profession: {
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
    color: '#15096F',
    opacity: 0.5,
  },
});
