import {StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
export default StyleSheet.create({
  MainView: {
    flex: 1,
    paddingHorizontal: 15,
    backgroundColor: '#ffff',
  },
  BigText: {
    color: '#5B77D0',
    fontSize: 40,
    alignSelf: 'center',
    marginTop: 30,
    fontFamily: 'Poppins-Bold',
  },
  MediumText: {
    color: '#15096F',
    fontSize: 16,
    alignSelf: 'center',
    marginTop: 0,
    fontFamily: 'Poppins-Medium',
  },
  SmallText: {
    color: '#15096F',
    fontSize: 12,
    alignSelf: 'center',
    marginTop: 10,
  },
  SmallTextBold: {
    color: '#15096F',
    fontSize: 12,
    alignSelf: 'center',
    marginTop: 10,
    fontWeight: 'bold',
  },
  input: {
    height: hp(8),
    width: wp(70),
    borderWidth: 1,
    borderColor: '#15096F',
    alignSelf: 'center',
    borderRadius: 12,
    marginTop: 100,
    paddingHorizontal: 15,
    color: 'black',
    marginBottom: 100,
  },
  HeaderTopView: {
    flexDirection: 'row',
    paddingHorizontal: 15,
    width: wp(100),
    justifyContent: 'flex-end',
    paddingHorizontal: 30,
  },
  smallLogo: {
    height: 40,
    width: 60,
    alignSelf: 'flex-end',
    opacity: 0.6,
  },
  input: {
    height: hp(8),
    width: wp(70),
    borderWidth: 1,
    borderColor: '#15096F',
    alignSelf: 'center',
    borderRadius: 12,
    paddingHorizontal: 15,
    color: 'black',
    marginBottom: 10,
  },
  DDView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    height: hp(8),
    width: wp(70),
    borderWidth: 1,
    borderColor: '#15096F',
    alignSelf: 'center',
    borderRadius: 12,
    color: 'black',
    marginBottom: 10,
  },
  DDPickerView: {
    width: '80%',
    // borderWidth: 1,
    height: 50,
    borderTopEndRadius: 10,
    // marginTop: 10,
    borderBottomEndRadius: 10,
  },
  Error: {
    color: 'red',
    // alignSelf: 'center',
    paddingLeft: 40,
    fontSize: 12,
    fontFamily: 'Poppins-Regular',
  },
  DDIconView: {
    width: '20%',
    // borderWidth: 1,
    height: 50,
    borderTopStartRadius: 10,
    borderBottomStartRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  Picker: {
    height: hp(17),
    width: hp(17),
    borderRadius: 100,
  },
  RadioInnerView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  PickerView: {
    height: hp(18),
    width: hp(18),
    alignSelf: 'center',
    borderRadius: 70,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 10,
    borderRadius: 70,
  },
  CheckView: {
    flexDirection: 'row',
    height: hp(5),
    width: wp(100),
    alignSelf: 'center',
    marginTop: 10,
    // justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 38,
  },
  checkTxt: {
    fontSize: 12,
    color: '#15096F',
    fontFamily: 'Poppins-Regular',
  },
  checkTxtBold: {
    fontSize: 13,
    color: '#15096F',
    fontFamily: 'Poppins-SemiBold',
  },
  RadioLatbel: {
    fontSize: 12,
    color: 'black',
  },
});
