import {StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
export default StyleSheet.create({
  bg: {
    flex: 1,
    height: '50%',
  },
  BigText: {
    color: '#fff',
    fontSize: 30,
    fontFamily: 'Poppins-SemiBold',
    alignSelf: 'center',
  },
  MediumText: {
    color: 'white',
    fontSize: 20,
    alignSelf: 'center',
    marginTop: 10,
    textAlign: 'center',
  },
  SmallText: {
    color: '#5B77D0',
    fontSize: 14,
    alignSelf: 'center',
    marginTop: 10,
  },
  SmallTextBold: {
    color: 'white',
    fontSize: 20,
    alignSelf: 'center',
    fontWeight: 'bold',
  },
  inputView: {
    height: hp(8),
    width: wp(85),
    alignSelf: 'center',
    borderRadius: 10,
    backgroundColor: '#5B77D0',
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  input: {
    height: hp(8),
    width: wp(70),
    alignSelf: 'center',
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    color: 'white',
    backgroundColor: '#5B77D0',
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#fff',
  },
  SearchBtn: {
    height: hp(8),
    width: wp(15),
    borderWidth: 1,
    borderColor: '#fff',
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },

  Peragraph: {
    height: hp(20),
    width: wp(85),
    alignSelf: 'center',
    borderRadius: 10,
    color: 'black',
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    marginTop: 10,
    borderWidth: 1,
  },
  smallLogo: {
    height: 50,
    width: 60,
    alignSelf: 'flex-end',
    right: 10,
    opacity: 0.3,
  },
  FlatListCard: {
    height: hp(10),
    width: wp(90),
    alignSelf: 'center',
    borderRadius: 10,
    marginTop: 5,
    marginBottom: 15,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    justifyContent: 'space-between',
    elevation: 2,
    flexDirection: 'row',
  },
  FlatListCardTxt: {
    color: 'black',
    fontSize: 19,
    alignSelf: 'center',
    fontWeight: 'bold',
  },
  GreenDot: {
    height: 15,
    width: 15,
    backgroundColor: 'green',
    borderRadius: 10,
  },
  smallCard: {
    height: hp(8),
    width: wp(86),
    alignSelf: 'center',
    borderRadius: 10,
    marginTop: 5,
    marginBottom: 5,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#5B77D0',
    justifyContent: 'center',
    elevation: 4,
  },

  SmallRoundPic: {
    height: 40,
    width: 40,
    borderRadius: 60,
  },
  HeaderTopView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: wp(100),
    alignItems: 'center',
  },
  filterView: {
    height: hp(5),
    width: wp(7),
    alignSelf: 'flex-end',
    borderWidth: 0,
    marginTop: hp(38),
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    right: 20,
    top: 50,
  },
  jobsDoneTxt: {
    fontSize: 10,
    marginTop: 15,
    color: '#15096F',
    fontFamily: 'Poppins-Regular',
    opacity: 0.4,
  },
  name: {
    fontSize: 16,
    fontFamily: 'Poppins-SemiBold',
    color: '#15096F',
  },
  Regular: {
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
    color: '#15096F',
    opacity: 0.4,
  },

  bg: {
    flex: 1,
    height: hp('50%'),
  },
  BigText: {
    color: '#fff',
    fontSize: 30,
    alignSelf: 'center',
    fontFamily: 'Poppins-SemiBold',
    marginTop: 10,
  },

  smallLogo: {
    height: 50,
    width: 60,
    alignSelf: 'flex-end',
    right: 10,
    opacity: 0.3,
  },
  InputsView: {
    paddingHorizontal: 15,
    marginBottom: 30,
    flex: 1,
  },
  HeadinOnly: {
    fontSize: 16,
    fontFamily: 'Poppins-Medium',
    color: '#15096F',
  },
  RatingsTxt: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'black',
  },
  RatingView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
    marginBottom: 10,
  },
  Input: {
    height: hp(8),
    width: wp('90%'),
    borderWidth: 1,
    backgroundColor: '#fff',
    color: 'black',
    paddingHorizontal: 12,
    borderRadius: 5,
    marginTop: 10,
  },
  Btn: {
    height: hp(6),
    width: wp('55%'),
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    backgroundColor: '#5B77D0',
    marginBottom: 30,
    marginTop: 40,
  },
  BtnTxt: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  ModalBtn: {
    height: hp(8),
    width: wp('80%'),
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    backgroundColor: '#5B77D0',
    marginTop: hp(5),
  },
  ModalBtnTxt: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
});
