import {StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
export default StyleSheet.create({
  bg: {
    flex: 1,
    height: '38%',
  },
  MediumText: {
    color: 'white',
    fontSize: 22,
    fontFamily: 'Poppins-Bold',
  },
  MediumTextBlur: {
    color: 'white',
    fontSize: 18,
    opacity: 0.6,
    fontFamily: 'Poppins-Medium',
    bottom: 5,
  },
  HeaderTopView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: wp(100),
    alignItems: 'center',
    paddingHorizontal: 15,
    marginTop: 50,
    paddingTop: 10,
  },
  PickerView: {
    height: hp(15),
    width: hp(15),
    borderRadius: 70,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 60,
    right: 10,
    borderWidth: 0,
  },
  Picker: {
    height: hp(15),
    width: wp(26),
    borderRadius: 70,
  },
  ImageView: {
    flexDirection: 'row',
    paddingHorizontal: wp(10),
    height: hp('18%'),
    alignItems: 'center',
  },

  RatingView: {
    marginTop: hp('2%'),
    height: hp('100%'),
    width: wp('90%'),
    alignSelf: 'center',
    elevation: 4,
    backgroundColor: '#fff',
    marginBottom: 30,
    borderRadius: 10,
  },
  RatingTxt: {
    fontSize: 14,
    fontFamily: 'Poppins-SemiBold',
    alignSelf: 'center',
    marginBottom: 7,
    marginTop: 7,
    color: '#1C876A',
  },
  smallTextBold: {
    fontSize: 16,
    fontFamily: 'Poppins-SemiBold',
    alignSelf: 'center',
    color: '#15096F',
    marginBottom: 10,
  },
  jobfinish: {
    fontSize: 25,
    fontFamily: 'Poppins-SemiBold',
    alignSelf: 'center',
    color: '#1C876A',
    marginTop: 15,
  },

  StarView: {
    height: 30,
    width: 150,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 0,
  },
  StarRatingView: {
    height: hp(4.5),
    width: wp(50),
    alignSelf: 'center',
  },
  Peragraph: {
    borderWidth: 0,
    height: 100,
    width: '80%',
    alignSelf: 'center',
    marginTop: 10,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.5,
    shadowRadius: 2,
    elevation: 2,
    backgroundColor: '#F4F4FA',
    paddingHorizontal: 12,
  },
  Btn: {
    height: hp(6),
    width: wp('55%'),
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    backgroundColor: '#5B77D0',
    marginBottom: 30,
    marginTop: 40,
  },
  BtnTxt: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
});
