// import colors from '@App/constants/colors';
import {StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';

export default StyleSheet.create({
  screen: {
    flex: 1,
    justifyContent: 'flex-end',
    padding: 15,
    backgroundColor: '#F4F4FA',
    // marginTop: hp(0),
  },
  messageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 8,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 40,
  },
  message: {
    backgroundColor: '#fff',
    paddingVertical: 10,
    // paddingHorizontal: 40,
    minWidth: 170,
    borderRadius: 20,
    // color: 'red',
    // fontFamily: 'Poppins-Medium',
    fontSize: 15,
    // textAlign: 'left',
  },
  inverted: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flex: 1,
  },
  inputContainer: {
    backgroundColor: '#fff',
    borderRadius: 5,
    // backgroundColor: 'red',
    // bottom: 300,
    height: 45,
    alignItems: 'center',
    width: '100%',
    // marginBottom: 50,
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    flexDirection: 'row',
  },
  input: {
    flex: 1,
    color: 'black',
    fontFamily: 'Segoe UI',
    fontSize: 15,
  },
  send: {
    width: 20,
    height: 20,
  },
  bg: {
    flex: 1,
    height: '42%',
  },
  MediumText: {
    color: 'white',
    fontSize: 22,
    fontFamily: 'Poppins-Bold',
  },
  MediumTextBlur: {
    color: 'white',
    fontSize: 18,
    opacity: 0.6,
    fontFamily: 'Poppins-Medium',
    bottom: 5,
  },
  HeaderTopView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: wp(100),
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingTop: 10,
  },
  PickerView: {
    height: hp(12),
    width: hp(12),
    // justifyContent: 'center',
    // alignItems: 'center',
    borderRadius: 100,
    right: 10,
  },
  EditTxt: {
    color: 'white',
    opacity: 0.5,
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
    bottom: 5,
  },
  StartCountTxt: {
    fontSize: 14,
    fontFamily: 'Poppins-Medium',
    color: 'white',
    left: 10,
  },
  Picker: {
    height: hp(12),
    width: hp(12),
    borderRadius: 70,
  },
  MediumText2: {
    color: 'white',
    fontSize: 18,
    marginTop: 0,
    fontFamily: 'Poppins-Bold',
  },
  ImageView: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    // backgroundColor: 'red',
    borderWidth: 0,
    paddingHorizontal: 30,
    marginTop: 30,
  },
  OfferJob: {
    height: hp(4),
    width: wp('25%'),
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 3,
  },
  OfferJobTxt: {
    fontSize: 12,
    color: '#15096F',
    fontFamily: 'Poppins-Medium',
  },
  ModalView: {
    height: hp('68%'),
    width: wp('90%'),
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 10,
    paddingVertical: 20,
  },
  ModalHeadingTxt: {
    color: '#15096F',
    fontSize: 25,
    fontFamily: 'Poppins-SemiBold',
    alignSelf: 'center',
    letterSpacing: 0,
    // marginBottom: 10
  },
  ModalInput: {
    height: hp(8),
    width: wp('80%'),
    alignSelf: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderRadius: 10,
    marginTop: 10,
    paddingHorizontal: 10,
    borderColor: '#15096F',
    fontFamily: 'Poppins-Regular',
  },
  ModalPeragraph: {
    height: hp(15),
    width: wp('80%'),
    alignSelf: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderRadius: 10,
    textAlignVertical: 'top',
    marginTop: 10,
    paddingHorizontal: 10,
    borderColor: '#15096F',
    fontFamily: 'Poppins-Regular',
  },
  DropDown: {
    height: hp(8),
    width: wp('70%'),
    alignSelf: 'center',
    marginTop: 10,
  },
  ContainerStyle: {
    height: hp(8),
    width: wp('70%'),
    alignSelf: 'center',
  },
  ModalBtn: {
    height: hp(8),
    width: wp('70%'),
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    backgroundColor: '#5B77D0',
    marginTop: 50,
  },
  ModalBtnTxt: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  StarView: {
    height: 30,
    width: 150,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  Timer: {
    color: 'white',
    fontSize: 14,
    fontFamily: 'Poppins-Medium',
    alignSelf: 'flex-end',
    paddingRight: 15,
    top: 10,
  },
  RatingView: {
    marginTop: hp('2%'),
    height: hp('100%'),
    width: wp('90%'),
    alignSelf: 'center',
    elevation: 4,
    backgroundColor: '#fff',
    marginBottom: 30,
    borderRadius: 10,
  },
  RatingTxt: {
    fontSize: 14,
    fontFamily: 'Poppins-SemiBold',
    alignSelf: 'center',
    marginBottom: 7,
    marginTop: 7,
    color: '#1C876A',
  },
  smallTextBold: {
    fontSize: 16,
    fontFamily: 'Poppins-SemiBold',
    alignSelf: 'center',
    color: '#15096F',
    bottom: 10,
  },
  jobfinish: {
    fontSize: 25,
    fontFamily: 'Poppins-SemiBold',
    alignSelf: 'center',
    color: '#1C876A',
    marginTop: 15,
  },
  Btn: {
    height: hp(6),
    width: wp('60%'),
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    backgroundColor: '#5B77D0',
    marginTop: 50,
  },
  BtnTxt: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  StarView: {
    height: 30,
    width: 150,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 0,
  },
  StarRatingView: {
    height: hp(4.5),
    width: wp(50),
    alignSelf: 'center',
  },
  AddMoreTxt: {
    alignSelf: 'flex-end',
    fontSize: 16,
    FontFamily: 'Poppins-Medium',
    marginTop: 10,
    right: 30,
    color: '#15096F',
    opacity: 0.4,
  },
  ReciveSmsView: {
    // height: hp(10),
    width: wp(80),
    alignSelf: 'flex-start',
    backgroundColor: '#fff',
    borderRadius: 7,
    // marginBottom: 0,
    marginTop: 15,
    justifyContent: 'center',
    paddingHorizontal: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    // alignItems: 'center'
  },
  SendSmsView: {
    // height: hp(12),
    width: wp(80),
    alignSelf: 'flex-end',
    backgroundColor: '#fff',
    borderRadius: 7,
    paddingHorizontal: 5,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    // alignItems: 'center',
    marginTop: 10,
  },
  SmsReciveAvatar: {
    height: 40,
    width: 40,
    borderRadius: 10,
    top: 5,
  },
  ReciveSmsInnerView: {
    // height: hp(7),
    alignSelf: 'center',
    borderWidth: 0,
    width: wp('65%'),
  },
  name: {
    fontSize: 16,
    fontFamily: 'Poppins-SemiBold',
    color: '#15096F',
  },
  Mesg: {
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
    bottom: 5,
    color: 'black',
  },
  Time: {
    fontSize: 10,
    fontFamily: 'Poppins-Regular',
    bottom: 2,
    color: '#A19DC5',
    marginRight: 10,
  },
  SmsSendAvatar: {
    height: 40,
    width: 40,
    borderRadius: 10,
    marginLeft: 5,
    top: 5,
  },
  SendSmsInnerView: {
    // height: hp(7),
    alignSelf: 'center',
    borderWidth: 0,
    width: wp('65%'),
    alignItems: 'flex-end',
  },
  ChatInputView: {
    height: hp(8),
    backgroundColor: '#F4F4F4',
    elevation: 2,
    flexDirection: 'row',
    borderWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  MsgInput: {
    height: hp(6),
    width: wp(80),
    borderWidth: 0,
    marginTop: hp(1),
    paddingHorizontal: 15,
    fontFamily: 'Poppins-Regulr',
  },
  sendBtnTxt: {
    fontSize: 14,
    fontFamily: 'Poppins-Medium',
    color: '#1c876a',
  },
});
